<a href="https://colab.research.google.com/github/VivekChaurasiya95/DecodeLabs-Internship/blob/main/Decodelabs_Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving customer_shopping_data.csv to customer_shopping_data.csv

In [3]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv('customer_shopping_data.csv')
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

In [11]:
df.shape

(99457, 10)

In [6]:
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 7.6+ MB

In [8]:
df.isnull().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [12]:
df.describe()

                age      quantity         price
count  99457.000000  99457.000000  99457.000000
mean      43.427089      3.003429    689.256321
std       14.990054      1.413025    941.184567
min       18.000000      1.000000      5.230000
25%       30.000000      2.000000     45.450000
50%       43.000000      3.000000    203.300000
75%       56.000000      4.000000   1200.320000
max       69.000000      5.000000   5250.000000

In [14]:
df.sample(5)

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
28236,I114889,C292683,Female,62,Clothing,3,900.24,Cash,12/7/2022,Metrocity
58853,I221614,C300752,Female,21,Cosmetics,4,162.64,Cash,19/11/2021,Cevahir AVM
76702,I373747,C211296,Male,30,Technology,1,1050.00,Cash,21/12/2022,Kanyon
79576,I271312,C337929,Male,62,Clothing,5,1500.40,Cash,25/02/2021,Kanyon
55312,I197905,C222688,Female,45,Food & Beverage,3,15.69,Credit Card,19/02/2022,Mall of Istanbul
49446,I155101,C112441,Male,46,Food & Beverage,5,26.15,Cash,4/2/2022,Kanyon
30409,I331788,C729877,Male,28,Food & Beverage,3,15.69,Debit Card,5/10/2021,Emaar Square Mall
13147,I214664,C115389,Male,48,Clothing,3,900.24,Cash,14/01/2023,Cevahir AVM
60422,I242518,C279650,Male,66,Clothing,3,900.24,Cash,3/8/2021,Kanyon
5554,I135483,C108683,Male,59,Cosmetics,1,40.66,Debit Card,7/9/2021,Metrocity

In [16]:
df.nunique()

invoice_no        99457
customer_id       99457
gender                2
age                  52
category              8
quantity              5
price                40
payment_method        3
invoice_date        797
shopping_mall        10
dtype: int64

In [17]:
df['category'].value_counts()

category
Clothing           34487
Cosmetics          15097
Food & Beverage    14776
Toys               10087
Shoes              10034
Souvenir            4999
Technology          4996
Books               4981
Name: count, dtype: int64

In [19]:
df['gender'].value_counts()

gender
Female    59482
Male      39975
Name: count, dtype: int64

In [20]:
df['payment_method'].value_counts()

payment_method
Cash           44447
Credit Card    34931
Debit Card     20079
Name: count, dtype: int64

In [21]:
df['shopping_mall'].value_counts()

shopping_mall
Mall of Istanbul     19943
Kanyon               19823
Metrocity            15011
Metropol AVM         10161
Istinye Park          9781
Zorlu Center          5075
Cevahir AVM           4991
Forum Istanbul        4947
Viaport Outlet        4914
Emaar Square Mall     4811
Name: count, dtype: int64